### PR TITLE
Added deriver option fields to generate key fields module

### PR DESCRIPTION
**Pull request by stevebleazard**
The deriver option `fields` (`[@@deriving yojson { fields = true }]`) has been added. This generates a new module, `Yojson_fields`, containing the value `keys`, a string list of all the JSON keys.

A module was created for a couple of reasons: This allows other fields values/functions to be added later and it mirrors `[@@deriving fields]`.

Thus given
```ocaml
module Bar_to_only = struct
  type t = {
     fvalue : float
   ; svalue : string [@key "@svalue_json"]
   ; ivalue : int
  } [@@deriving to_yojson { strict = false } ]
end
```
The following module is generated:
```ocaml
module Yojson_fields = struct
  let keys = ["fvalue"; "@svalue_json"; "ivalue"] 
  let _ = keys 
end
```

### CODE REVIEW

**Comment by whitequark** [comment]
How does this work for `type a = ... and b = ... [@@deriving yojson { fields = true }]` exactly?

**Comment by stevebleazard** [comment]
It looks like the travis CI integration has issues:
```
The actions to process have cyclic dependencies:
  - ⊘  ocaml-migrate-parsetree.1.0.7 -> ⊘  jbuilder.1.0+beta17 -> ⊘  ocaml-migrate-parsetree.1.0.7
```

**Comment by whitequark** [comment]
It's an opam repository bug. https://github.com/ocaml/opam-repository/issues/11365

**Comment by stevebleazard** [comment]
Here's an example of `type a = ... and b = ... [@@deriving yojson { fields = true }]`:
```ocaml
module Whitequark = struct
  type a = {
    w : int
  ; x : char [@key "x_in_a"]
  }
  and b = {
    y : float
  ; z : string [@key "z_in_b"]
  } [@@deriving yojson { fields = true }]
end
```
becomes
```ocaml
module Whitequark = struct
  ...
  module Yojson_fields_a = struct
    let keys = ["w"; "x_in_a"] 
    let _ = keys
  end

  module Yojson_fields_b = struct
    let keys = ["y"; "z_in_b"] 
    let _ = keys
  end
  ...
end
```

**Comment by whitequark** [comment]
When is this useful exactly?

**Comment by stevebleazard** [comment]
When interfacing with some search engines and databases being able to specify the keys to be returned can be a major win in performance and amount of data transferred. Elastic search is a good example of where I've used this.

**Comment by whitequark** [comment]
I've edited documentation slightly.

Should the module be called `Yojson_fields`? What if later we want to add something that isn't related to *fields* per se? How about `Yojson_meta` instead?

**Comment by stevebleazard** [comment]
Yojson_meta sounds good, I'll update and fix any references

**Comment by whitequark** [comment]
Thanks!

**Pull request merged**
